# Generated by Django 4.1.3 on 2022-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default='0000000000'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default='12345'),
        ),
    ]
