# Generated by Django 4.1.3 on 2022-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_options_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
