# Generated by Django 4.1.3 on 2022-12-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_storageunit_available_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='size',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='type',
            field=models.CharField(choices=[('A', '5m2 first floor'), ('B', '6m2 first floor')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='price',
            field=models.CharField(max_length=5),
        ),
    ]
