# Generated by Django 4.1.3 on 2022-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_storageunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunit',
            name='type',
            field=models.CharField(choices=[('5m2 first floor', 'S 1:st floor'), ('6m2 first floor', 'M 1:st floor'), ('10m2 first floor', 'L 1:st floor'), ('5m2 second floor', 'S 2:nd floor'), ('6m2 second floor', 'M 2:nd floor'), ('10m2 second floor', 'L 2:nd floor'), ('12m2 second floor', 'XL 2:nd floor')], max_length=100),
        ),
    ]
