# Generated by Django 4.1.3 on 2022-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_storageunit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='orgnr',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='personnr',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
