# Generated by Django 4.1.3 on 2022-12-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_company_customer_orgnr_customer_personnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orgnr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personnr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
