# Generated by Django 4.1.3 on 2022-12-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
