# Generated by Django 4.1.3 on 2022-12-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_customer_password_remove_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orgnr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personnr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
