# Generated by Django 4.1.3 on 2022-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_storageunit_floor_storageunit_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='name',
            field=models.CharField(choices=[('S1', 'S1'), ('M1', 'M1'), ('L1', 'L1'), ('S2', 'S2'), ('M2', 'M2'), ('L2', 'S2'), ('XL2', 'XL2')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
