# Generated by Django 4.1.3 on 2022-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunit',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
