# Generated by Django 4.1.3 on 2022-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_storageunit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunit',
            name='price',
            field=models.IntegerField(),
        ),
    ]
