# Generated by Django 4.1.3 on 2022-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='type',
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='name',
            field=models.CharField(choices=[('Small 1st floor', 'Small 1st floor'), ('Medium 1st floor', 'Medium 1st floor'), ('Large 1st floor', 'Large 1st floor'), ('Small 2nd floor', 'Small 2nd floor'), ('Medium 2nd floor', 'Medium 2nd floor'), ('Large 2nd floor', 'Large 2nd floor'), ('X-Large 2nd floor', 'X-Large 2nd floor')], max_length=100),
        ),
    ]
