# Generated by Django 4.1.3 on 2022-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_storageunit_type_alter_storageunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
