# Generated by Django 4.1.3 on 2022-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_storageunit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='type',
        ),
    ]
