# Generated by Django 4.1.3 on 2022-12-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_storageunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orgnr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personnr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
