# Generated by Django 4.1.3 on 2022-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orgnr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='personnr',
        ),
        migrations.AddField(
            model_name='customer',
            name='person_or_org_nr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
